[project]
name = "q-and-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=5.2.2",
    "icecream>=2.1.3",
    "mypy>=1.13.0",
    "ruff>=0.8.2",
    "virtualenv>=20.28.0",
]
